"""empty message

Revision ID: 09f8c130c8d3
Revises: 9cc5b1dd048f
Create Date: 2022-10-27 14:40:03.730359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f8c130c8d3'
down_revision = '9cc5b1dd048f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
