"""empty message

Revision ID: 9cc5b1dd048f
Revises: d659a14689c9
Create Date: 2022-10-27 14:11:54.373655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc5b1dd048f'
down_revision = 'd659a14689c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moons', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'moons')
    # ### end Alembic commands ###
