"""empty message

Revision ID: d5a039d974c3
Revises: 09f8c130c8d3
Create Date: 2022-10-27 14:45:47.396186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a039d974c3'
down_revision = '09f8c130c8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
